stages:
  - test

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pytest pytest-cov httpx pytest-asyncio
  script:
    - pytest --cov=routes.api.igus --cov-report=term-missing
  artifacts:
    paths:
      - .coverage
    when: always
