name: Run Pytest and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov httpx pytest-asyncio

    - name: Run tests
      run: |
        pytest --cov=routes.api.igus --cov-report=term-missing

    # По желанию: Сохрани coverage-отчет как артефакт
    - name: Archive coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: .coverage
